package com.android.internal.art;

/* JADX INFO: loaded from: classes.dex */
public final class ArtStatsLog {
    public static final byte ANNOTATION_ID_DEFAULT_STATE = 6;
    public static final byte ANNOTATION_ID_EXCLUSIVE_STATE = 4;
    public static final byte ANNOTATION_ID_IS_UID = 1;
    public static final byte ANNOTATION_ID_PRIMARY_FIELD = 3;
    public static final byte ANNOTATION_ID_PRIMARY_FIELD_FIRST_UID = 5;
    public static final byte ANNOTATION_ID_STATE_NESTED = 8;
    public static final byte ANNOTATION_ID_TRIGGER_STATE_RESET = 7;
    public static final byte ANNOTATION_ID_TRUNCATE_TIMESTAMP = 2;
    public static final int ART_DATUM_DELTA_REPORTED = 565;
    public static final int ART_DATUM_DELTA_REPORTED__APK_TYPE__ART_APK_TYPE_BASE = 1;
    public static final int ART_DATUM_DELTA_REPORTED__APK_TYPE__ART_APK_TYPE_SPLIT = 2;
    public static final int ART_DATUM_DELTA_REPORTED__APK_TYPE__ART_APK_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_AB_OTA = 7;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BG_DEXOPT = 6;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT = 4;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_MAINLINE_UPDATE = 21;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_OAT_FORCE = 27;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_OTA = 17;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_CMDLINE = 19;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_COMPENSATE_DEX = 25;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_ERROR = 1;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_EXTRA_SECOND_DEX = 24;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_FIRST_BOOT = 3;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INACTIVE = 8;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL = 5;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK = 13;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_DOWNGRADED = 15;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY = 14;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY_DOWNGRADED = 16;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_FAST = 12;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_WITH_DEX_METADATA = 10;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_POST_BOOT = 11;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_PREBUILT = 18;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_REPAIR_DEX = 26;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_SECOND_DEX = 23;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_SHARED = 9;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_START_APP = 22;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_UNKNOWN = 2;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_UNSPECIFIED = 0;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_VDEX = 20;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_ASSUMED_VERIFIED = 3;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_ERROR = 1;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EVERYTHING = 12;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EVERYTHING_PROFILE = 11;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EXTRACT = 4;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_APK = 13;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_APK_FALLBACK = 14;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_VDEX_FALLBACK = 15;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_QUICKEN = 6;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPACE = 8;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPACE_PROFILE = 7;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPEED = 10;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPEED_PROFILE = 9;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_UNKNOWN = 2;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_UNSPECIFIED = 0;
    public static final int ART_DATUM_DELTA_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_VERIFY = 5;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_ERROR = 5;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_NONE = 4;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_PROFILE = 1;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_PROFILE_AND_VDEX = 3;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_DELTA_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_VDEX = 2;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_COPYING = 5;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_COPYING_BACKGROUND = 6;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_COMPACT = 3;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_COMPACT_BACKGROUND = 7;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_SWEEP = 2;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_MARK_SWEEP = 1;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_SEMI_SPACE = 4;
    public static final int ART_DATUM_DELTA_REPORTED__GC__ART_GC_COLLECTOR_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_ARM = 1;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_ARM64 = 2;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_MIPS = 5;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_MIPS64 = 6;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_RISCV64 = 7;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_UNKNOWN = 0;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_X86 = 3;
    public static final int ART_DATUM_DELTA_REPORTED__ISA__ART_ISA_X86_64 = 4;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_CLASS_LOADING_TIME_MICROS = 9;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_CLASS_VERIFICATION_COUNT = 16;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_CLASS_VERIFICATION_TIME_MICROS = 8;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_FULL_HEAP_COLLECTION_COUNT = 5;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_FULL_HEAP_COLLECTION_DURATION_MS = 36;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_FULL_HEAP_COLLECTION_FREED_BYTES = 35;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_FULL_HEAP_COLLECTION_SCANNED_BYTES = 34;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_TOTAL_BYTES_ALLOCATED = 17;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_TOTAL_COLLECTION_TIME_MS = 28;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_WORLD_STOP_COUNT = 30;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_WORLD_STOP_TIME_US = 29;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_YOUNG_GENERATION_COLLECTION_COUNT = 3;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_YOUNG_GENERATION_COLLECTION_DURATION_MS = 33;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_YOUNG_GENERATION_COLLECTION_FREED_BYTES = 32;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_GC_YOUNG_GENERATION_COLLECTION_SCANNED_BYTES = 31;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_INVALID = 0;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_JIT_METHOD_COMPILE_COUNT = 21;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_JIT_METHOD_COMPILE_TIME_MICROS = 6;
    public static final int ART_DATUM_DELTA_REPORTED__KIND__ART_DATUM_DELTA_TIME_ELAPSED_MS = 37;
    public static final int ART_DATUM_DELTA_REPORTED__THREAD_TYPE__ART_THREAD_BACKGROUND = 2;
    public static final int ART_DATUM_DELTA_REPORTED__THREAD_TYPE__ART_THREAD_MAIN = 1;
    public static final int ART_DATUM_DELTA_REPORTED__THREAD_TYPE__ART_THREAD_UNKNOWN = 0;
    public static final int ART_DATUM_DELTA_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_MINOR_FAULT_MODE_NOT_SUPPORTED = 2;
    public static final int ART_DATUM_DELTA_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_MINOR_FAULT_MODE_SUPPORTED = 3;
    public static final int ART_DATUM_DELTA_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_UFFD_NOT_SUPPORTED = 1;
    public static final int ART_DATUM_DELTA_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED = 332;
    public static final int ART_DATUM_REPORTED__APK_TYPE__ART_APK_TYPE_BASE = 1;
    public static final int ART_DATUM_REPORTED__APK_TYPE__ART_APK_TYPE_SPLIT = 2;
    public static final int ART_DATUM_REPORTED__APK_TYPE__ART_APK_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_AB_OTA = 7;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BG_DEXOPT = 6;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT = 4;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_MAINLINE_UPDATE = 21;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_OAT_FORCE = 27;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_BOOT_AFTER_OTA = 17;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_CMDLINE = 19;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_COMPENSATE_DEX = 25;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_ERROR = 1;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_EXTRA_SECOND_DEX = 24;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_FIRST_BOOT = 3;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INACTIVE = 8;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL = 5;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK = 13;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_DOWNGRADED = 15;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY = 14;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_BULK_SECONDARY_DOWNGRADED = 16;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_FAST = 12;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_INSTALL_WITH_DEX_METADATA = 10;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_POST_BOOT = 11;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_PREBUILT = 18;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_REPAIR_DEX = 26;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_SECOND_DEX = 23;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_SHARED = 9;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_START_APP = 22;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_UNKNOWN = 2;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_UNSPECIFIED = 0;
    public static final int ART_DATUM_REPORTED__COMPILATION_REASON__ART_COMPILATION_REASON_VDEX = 20;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_ASSUMED_VERIFIED = 3;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_ERROR = 1;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EVERYTHING = 12;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EVERYTHING_PROFILE = 11;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_EXTRACT = 4;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_APK = 13;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_APK_FALLBACK = 14;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_FAKE_RUN_FROM_VDEX_FALLBACK = 15;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_QUICKEN = 6;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPACE = 8;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPACE_PROFILE = 7;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPEED = 10;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_SPEED_PROFILE = 9;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_UNKNOWN = 2;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_UNSPECIFIED = 0;
    public static final int ART_DATUM_REPORTED__COMPILE_FILTER__ART_COMPILATION_FILTER_VERIFY = 5;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_ERROR = 5;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_NONE = 4;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_PROFILE = 1;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_PROFILE_AND_VDEX = 3;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED__DEX_METADATA_TYPE__ART_DEX_METADATA_TYPE_VDEX = 2;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_COPYING = 5;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_COPYING_BACKGROUND = 6;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_COMPACT = 3;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_COMPACT_BACKGROUND = 7;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_CONCURRENT_MARK_SWEEP = 2;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_MARK_SWEEP = 1;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_SEMI_SPACE = 4;
    public static final int ART_DATUM_REPORTED__GC__ART_GC_COLLECTOR_TYPE_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_ARM = 1;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_ARM64 = 2;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_MIPS = 5;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_MIPS64 = 6;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_RISCV64 = 7;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_X86 = 3;
    public static final int ART_DATUM_REPORTED__ISA__ART_ISA_X86_64 = 4;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_AOT_COMPILE_TIME = 7;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_CLASS_LOADING_TIME_COUNTER_MICROS = 9;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_CLASS_VERIFICATION_COUNT = 16;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_CLASS_VERIFICATION_TIME_COUNTER_MICROS = 8;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_DEX_CODE_COUNTER_BYTES = 11;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_FAST_VERIFY_TIME_COUNTER_MILLIS = 14;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_RESOLVE_METHODS_AND_FIELDS_TIME_COUNTER_MILLIS = 15;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_RESULT_CODE = 10;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_TOTAL_TIME_COUNTER_MILLIS = 12;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_DEX2OAT_VERIFY_DEX_FILE_TIME_COUNTER_MILLIS = 13;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_COUNT = 5;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_DURATION_MS = 36;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_FREED_BYTES = 35;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_SCANNED_BYTES = 34;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_THROUGHPUT_AVG_MB_PER_SEC = 25;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_THROUGHPUT_HISTO_MB_PER_SEC = 20;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_COLLECTION_TIME_HISTO_MILLIS = 4;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_TRACING_THROUGHPUT_AVG_MB_PER_SEC = 27;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_FULL_HEAP_TRACING_THROUGHPUT_HISTO_MB_PER_SEC = 23;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_TOTAL_BYTES_ALLOCATED = 17;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_TOTAL_COLLECTION_TIME_MS = 28;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_TOTAL_METADATA_SIZE_BYTES = 18;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_WORLD_STOP_COUNT = 30;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_WORLD_STOP_TIME_AVG_MICROS = 1;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_WORLD_STOP_TIME_US = 29;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_COUNT = 3;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_DURATION_MS = 33;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_FREED_BYTES = 32;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_SCANNED_BYTES = 31;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_THROUGHPUT_AVG_MB_PER_SEC = 24;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_THROUGHPUT_HISTO_MB_PER_SEC = 19;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_COLLECTION_TIME_HISTO_MILLIS = 2;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_TRACING_THROUGHPUT_AVG_MB_PER_SEC = 26;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_GC_YOUNG_GENERATION_TRACING_THROUGHPUT_HISTO_MB_PER_SEC = 22;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_INVALID = 0;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_JIT_METHOD_COMPILE_COUNT = 21;
    public static final int ART_DATUM_REPORTED__KIND__ART_DATUM_JIT_METHOD_COMPILE_TIME_MICROS = 6;
    public static final int ART_DATUM_REPORTED__THREAD_TYPE__ART_THREAD_BACKGROUND = 2;
    public static final int ART_DATUM_REPORTED__THREAD_TYPE__ART_THREAD_MAIN = 1;
    public static final int ART_DATUM_REPORTED__THREAD_TYPE__ART_THREAD_UNKNOWN = 0;
    public static final int ART_DATUM_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_MINOR_FAULT_MODE_NOT_SUPPORTED = 2;
    public static final int ART_DATUM_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_MINOR_FAULT_MODE_SUPPORTED = 3;
    public static final int ART_DATUM_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_UFFD_NOT_SUPPORTED = 1;
    public static final int ART_DATUM_REPORTED__UFFD_SUPPORT__ART_UFFD_SUPPORT_UNKNOWN = 0;
    public static final int ART_DEVICE_DATUM_REPORTED = 550;
    public static final int ART_DEVICE_DATUM_REPORTED__BOOT_IMAGE_STATUS__STATUS_FULL = 1;
    public static final int ART_DEVICE_DATUM_REPORTED__BOOT_IMAGE_STATUS__STATUS_MINIMAL = 2;
    public static final int ART_DEVICE_DATUM_REPORTED__BOOT_IMAGE_STATUS__STATUS_NONE = 3;
    public static final int ART_DEVICE_DATUM_REPORTED__BOOT_IMAGE_STATUS__STATUS_UNSPECIFIED = 0;
    public static final int ART_DEVICE_STATUS = 10205;
    public static final int ART_DEVICE_STATUS__BOOT_IMAGE_STATUS__STATUS_FULL = 1;
    public static final int ART_DEVICE_STATUS__BOOT_IMAGE_STATUS__STATUS_MINIMAL = 2;
    public static final int ART_DEVICE_STATUS__BOOT_IMAGE_STATUS__STATUS_NONE = 3;
    public static final int ART_DEVICE_STATUS__BOOT_IMAGE_STATUS__STATUS_UNSPECIFIED = 0;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED = 467;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_APP_STANDBY = 12;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_BACKGROUND_RESTRICTION = 11;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CANCELLED_BY_APP = 1;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CONSTRAINT_BATTERY_NOT_LOW = 5;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CONSTRAINT_CHARGING = 6;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CONSTRAINT_CONNECTIVITY = 7;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CONSTRAINT_DEVICE_IDLE = 8;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_CONSTRAINT_STORAGE_NOT_LOW = 9;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_DEVICE_STATE = 4;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_ESTIMATED_APP_LAUNCH_TIME_CHANGED = 15;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_PREEMPT = 2;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_QUOTA = 10;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_SYSTEM_PROCESSING = 14;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_TIMEOUT = 3;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_UNDEFINED = 0;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__CANCELLATION_REASON__STOP_REASON_USER = 13;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__PASS__PASS_DOWNGRADE = 1;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__PASS__PASS_MAIN = 2;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__PASS__PASS_SUPPLEMENTARY = 3;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__PASS__PASS_UNKNOWN = 0;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORT_BATTERY = 5;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORT_BY_API = 6;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORT_BY_CANCELLATION = 2;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORT_NO_SPACE_LEFT = 3;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORT_THERMAL = 4;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_FATAL_ERROR = 7;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_JOB_FINISHED = 1;
    public static final int BACKGROUND_DEXOPT_JOB_ENDED__STATUS__STATUS_UNKNOWN = 0;
    public static final int EARLY_BOOT_COMP_OS_ARTIFACTS_CHECK_REPORTED = 419;
    public static final int ISOLATED_COMPILATION_ENDED = 458;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_COMPILATION_FAILED = 5;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_COMPOSD_DIED = 7;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_FAILED_TO_ENABLE_FSVERITY = 8;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_FAILED_TO_START = 3;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_JOB_CANCELED = 4;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_SUCCESS = 1;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_UNEXPECTED_COMPILATION_RESULT = 6;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_UNKNOWN = 0;
    public static final int ISOLATED_COMPILATION_ENDED__COMPILATION_RESULT__RESULT_UNKNOWN_FAILURE = 2;
    public static final int ISOLATED_COMPILATION_SCHEDULED = 457;
    public static final int ISOLATED_COMPILATION_SCHEDULED__SCHEDULING_RESULT__SCHEDULING_FAILURE = 1;
    public static final int ISOLATED_COMPILATION_SCHEDULED__SCHEDULING_RESULT__SCHEDULING_RESULT_UNKNOWN = 0;
    public static final int ISOLATED_COMPILATION_SCHEDULED__SCHEDULING_RESULT__SCHEDULING_SUCCESS = 2;
    public static final int ODREFRESH_REPORTED = 366;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_MAINLINE = 2;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_PRIMARY_AND_MAINLINE = 1;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_EXITED = 1;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_NOT_RUN = 5;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_SIGNALED = 2;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_START_FAILED = 4;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_TIMED_OUT = 3;
    public static final int ODREFRESH_REPORTED__PRIMARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_MAINLINE = 2;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_PRIMARY_AND_MAINLINE = 1;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_COMPILATION_TYPE__BCP_COMPILATION_TYPE_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_EXITED = 1;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_NOT_RUN = 5;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_SIGNALED = 2;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_START_FAILED = 4;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_TIMED_OUT = 3;
    public static final int ODREFRESH_REPORTED__SECONDARY_BCP_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_CHECK = 10;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_COMPLETE = 60;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_PREPARATION = 20;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_PRIMARY_BOOT_CLASSPATH = 30;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_SECONDARY_BOOT_CLASSPATH = 40;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_SYSTEM_SERVER_CLASSPATH = 50;
    public static final int ODREFRESH_REPORTED__STAGE_REACHED__STAGE_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_DALVIK_CACHE_PERMISSION_DENIED = 8;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_DEX2OAT_ERROR = 4;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_INSTALL_FAILED = 7;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_IO_ERROR = 3;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_NO_SPACE = 2;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_OK = 1;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_STAGING_FAILED = 6;
    public static final int ODREFRESH_REPORTED__STATUS__STATUS_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_EXITED = 1;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_NOT_RUN = 5;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_SIGNALED = 2;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_START_FAILED = 4;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_TIMED_OUT = 3;
    public static final int ODREFRESH_REPORTED__SYSTEM_SERVER_DEX2OAT_RESULT_STATUS__EXEC_RESULT_STATUS_UNKNOWN = 0;
    public static final int ODREFRESH_REPORTED__TRIGGER__TRIGGER_APEX_VERSION_MISMATCH = 1;
    public static final int ODREFRESH_REPORTED__TRIGGER__TRIGGER_DEX_FILES_CHANGED = 2;
    public static final int ODREFRESH_REPORTED__TRIGGER__TRIGGER_MISSING_ARTIFACTS = 3;
    public static final int ODREFRESH_REPORTED__TRIGGER__TRIGGER_UNKNOWN = 0;
    public static final int ODSIGN_REPORTED = 548;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_ALL_OK = 1;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_CERT_FAILED = 5;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_CLEANUP_FAILED = 6;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_KEYSTORE_FAILED = 4;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_ODREFRESH_FAILED = 3;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_PARTIAL_OK = 2;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_SIGNING_FAILED = 7;
    public static final int ODSIGN_REPORTED__STATUS__STATUS_UNSPECIFIED = 0;
    public static final int OPLUS_ART_LOCK_JANK_REPORTED = 100013;
    public static final int OPLUS_ART_THREAD_SLEEP_INFO_REPORTED = 100076;
    public static final int OPLUS_ART_VERIFIER_JANK_REPORTED = 100014;
    public static final int OPLUS_DEX_JANK_REPORTED = 100012;
    public static final int OPLUS_GC_BLOCKED_REPORTED = 100011;
    public static final int OPLUS_GC_INFO_STATISTICS = 100093;
    public static final int OPLUS_MONITOR_WAIT_INFO_REPORTED = 100134;
    public static final int PREREBOOT_DEXOPT_JOB_ENDED = 883;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__JOB_TYPE__JOB_TYPE_MAINLINE = 2;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__JOB_TYPE__JOB_TYPE_OTA = 1;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__JOB_TYPE__JOB_TYPE_UNKNOWN = 0;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_ABORTED_SYSTEM_REQUIREMENTS = 6;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_CANCELLED = 4;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_FAILED = 3;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_FINISHED = 2;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_NOT_SCHEDULED_DISABLED = 7;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_NOT_SCHEDULED_JOB_SCHEDULER = 8;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_SCHEDULED = 1;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_STARTED = 5;
    public static final int PRE_REBOOT_DEXOPT_JOB_ENDED__STATUS__STATUS_UNKNOWN = 0;

    public static void write(int code, boolean arg1, boolean arg2, boolean arg3) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeBoolean(arg1);
        builder.writeBoolean(arg2);
        builder.writeBoolean(arg3);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, int arg1) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, int arg1, int arg2, int arg3, int arg4, int arg5, long arg6, long arg7, int arg8, int arg9, int arg10, int arg11, int arg12) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeInt(arg4);
        builder.writeInt(arg5);
        builder.writeLong(arg6);
        builder.writeLong(arg7);
        builder.writeInt(arg8);
        builder.writeInt(arg9);
        builder.writeInt(arg10);
        builder.writeInt(arg11);
        builder.writeInt(arg12);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, int arg1, int arg2, long arg3, long arg4, int arg5, int arg6, int arg7, int arg8) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        builder.writeInt(arg2);
        builder.writeLong(arg3);
        builder.writeLong(arg4);
        builder.writeInt(arg5);
        builder.writeInt(arg6);
        builder.writeInt(arg7);
        builder.writeInt(arg8);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11, int arg12, int arg13, int arg14, int arg15, int arg16, int arg17, int arg18, int arg19, int arg20, int arg21, int arg22, int arg23) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeInt(arg4);
        builder.writeInt(arg5);
        builder.writeInt(arg6);
        builder.writeInt(arg7);
        builder.writeInt(arg8);
        builder.writeInt(arg9);
        builder.writeInt(arg10);
        builder.writeInt(arg11);
        builder.writeInt(arg12);
        builder.writeInt(arg13);
        builder.writeInt(arg14);
        builder.writeInt(arg15);
        builder.writeInt(arg16);
        builder.writeInt(arg17);
        builder.writeInt(arg18);
        builder.writeInt(arg19);
        builder.writeInt(arg20);
        builder.writeInt(arg21);
        builder.writeInt(arg22);
        builder.writeInt(arg23);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, int arg4, long arg5, int arg6, int arg7, long arg8, int arg9, int arg10, int arg11, int arg12, int arg13) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        if (332 == code) {
            builder.addBooleanAnnotation((byte) 1, true);
        }
        if (565 == code) {
            builder.addBooleanAnnotation((byte) 1, true);
        }
        builder.writeInt(arg3);
        builder.writeInt(arg4);
        builder.writeLong(arg5);
        builder.writeInt(arg6);
        builder.writeInt(arg7);
        builder.writeLong(arg8);
        builder.writeInt(arg9);
        builder.writeInt(arg10);
        builder.writeInt(arg11);
        builder.writeInt(arg12);
        builder.writeInt(arg13);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, int arg4, java.lang.String arg5, long arg6) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeInt(arg4);
        builder.writeString(arg5);
        builder.writeLong(arg6);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, long arg4, long arg5) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeLong(arg4);
        builder.writeLong(arg5);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, java.lang.String arg4, long arg5) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeString(arg4);
        builder.writeLong(arg5);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, java.lang.String arg4, java.lang.String arg5, long arg6) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeString(arg4);
        builder.writeString(arg5);
        builder.writeLong(arg6);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, int arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeInt(arg3);
        builder.writeString(arg4);
        builder.writeString(arg5);
        builder.writeString(arg6);
        builder.writeString(arg7);
        builder.writeString(arg8);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, long arg1, int arg2, long arg3, long arg4) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeLong(arg1);
        builder.writeInt(arg2);
        builder.writeLong(arg3);
        builder.writeLong(arg4);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static void write(int code, java.lang.String arg1, int arg2, java.lang.String arg3) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeString(arg1);
        builder.writeInt(arg2);
        builder.writeString(arg3);
        builder.usePooledBuffer();
        android.util.StatsLog.write(builder.build());
    }

    public static android.util.StatsEvent buildStatsEvent(int code, int arg1) {
        android.util.StatsEvent.Builder builder = android.util.StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        return builder.build();
    }
}
