package com.android.server.am;

/* JADX INFO: loaded from: classes.dex */
public class ActivityManagerDebugConfig {
    public static boolean DEBUG_ALLOWLISTS = false;
    public static boolean DEBUG_BACKGROUND_CHECK = false;
    public static boolean DEBUG_BACKUP = false;
    public static boolean DEBUG_BROADCAST = false;
    public static boolean DEBUG_BROADCAST_BACKGROUND = false;
    public static boolean DEBUG_BROADCAST_DEFERRAL = false;
    public static boolean DEBUG_BROADCAST_LIGHT = false;
    public static boolean DEBUG_COMPACTION = false;
    public static boolean DEBUG_FOREGROUND_SERVICE = false;
    public static boolean DEBUG_FREEZER = false;
    public static boolean DEBUG_LRU = false;
    public static boolean DEBUG_MU = false;
    public static boolean DEBUG_NETWORK = false;
    public static boolean DEBUG_OOM_ADJ = false;
    public static boolean DEBUG_OOM_ADJ_REASON = false;
    public static boolean DEBUG_PERMISSIONS_REVIEW = false;
    public static boolean DEBUG_POWER = false;
    public static boolean DEBUG_POWER_QUICK = false;
    public static boolean DEBUG_PROCESSES = false;
    public static boolean DEBUG_PROCESS_OBSERVERS = false;
    public static boolean DEBUG_PROVIDER = false;
    public static boolean DEBUG_PSS = false;
    public static boolean DEBUG_RSS = false;
    public static boolean DEBUG_SERVICE = false;
    public static boolean DEBUG_SERVICE_EXECUTING = false;
    public static boolean DEBUG_UID_OBSERVERS = false;
    public static boolean DEBUG_USAGE_STATS = false;
    static final java.lang.String POSTFIX_BACKUP;
    static final java.lang.String POSTFIX_BROADCAST;
    static final java.lang.String POSTFIX_CLEANUP;
    static final java.lang.String POSTFIX_LRU;
    static final java.lang.String POSTFIX_MU = "_MU";
    static final java.lang.String POSTFIX_NETWORK = "_Network";
    static final java.lang.String POSTFIX_OOM_ADJ;
    static final java.lang.String POSTFIX_POWER;
    static final java.lang.String POSTFIX_PROCESSES;
    static final java.lang.String POSTFIX_PROCESS_OBSERVERS;
    static final java.lang.String POSTFIX_PSS;
    static final java.lang.String POSTFIX_RSS;
    static final java.lang.String POSTFIX_SERVICE;
    static final java.lang.String POSTFIX_SERVICE_EXECUTING;
    static final java.lang.String POSTFIX_UID_OBSERVERS;
    static final java.lang.String TAG_AM = "ActivityManager";
    static final boolean TAG_WITH_CLASS_NAME = false;
    public static boolean APPEND_CATEGORY_NAME = false;
    static final java.io.PrintWriter LOG_WRITER_INFO = new java.io.PrintWriter((java.io.Writer) new android.util.LogWriter(4, "ActivityManager"));
    public static boolean DEBUG_ALL = false;
    private static final boolean DEBUG_VERSION = "userdebug".equals(android.os.SystemProperties.get("ro.build.type"));
    public static boolean DEBUG_AMS = android.os.SystemProperties.getBoolean("persist.sys.assert.panic", false);
    public static boolean DEBUG_ANR = false;

    static {
        DEBUG_BACKGROUND_CHECK = DEBUG_ALL;
        DEBUG_BACKUP = DEBUG_ALL;
        DEBUG_BROADCAST = DEBUG_ALL;
        DEBUG_BROADCAST_BACKGROUND = DEBUG_BROADCAST;
        DEBUG_BROADCAST_LIGHT = DEBUG_BROADCAST;
        DEBUG_BROADCAST_DEFERRAL = DEBUG_BROADCAST;
        DEBUG_COMPACTION = DEBUG_ALL;
        DEBUG_FREEZER = true;
        DEBUG_LRU = DEBUG_ALL;
        DEBUG_MU = DEBUG_ALL;
        DEBUG_NETWORK = DEBUG_ALL;
        DEBUG_OOM_ADJ = DEBUG_ALL;
        DEBUG_OOM_ADJ_REASON = DEBUG_ALL;
        DEBUG_POWER = DEBUG_ALL;
        DEBUG_POWER_QUICK = DEBUG_POWER;
        DEBUG_PROCESS_OBSERVERS = DEBUG_ALL;
        DEBUG_PROCESSES = DEBUG_ALL;
        DEBUG_PROVIDER = DEBUG_ALL;
        DEBUG_PSS = DEBUG_ALL;
        DEBUG_RSS = DEBUG_ALL;
        DEBUG_SERVICE = DEBUG_ALL;
        DEBUG_FOREGROUND_SERVICE = DEBUG_ALL;
        DEBUG_SERVICE_EXECUTING = DEBUG_ALL;
        DEBUG_UID_OBSERVERS = DEBUG_ALL;
        DEBUG_USAGE_STATS = DEBUG_ALL;
        DEBUG_PERMISSIONS_REVIEW = DEBUG_ALL;
        DEBUG_ALLOWLISTS = DEBUG_ALL;
        POSTFIX_BACKUP = APPEND_CATEGORY_NAME ? "_Backup" : "";
        POSTFIX_BROADCAST = APPEND_CATEGORY_NAME ? "_Broadcast" : "";
        POSTFIX_CLEANUP = APPEND_CATEGORY_NAME ? "_Cleanup" : "";
        POSTFIX_LRU = APPEND_CATEGORY_NAME ? "_LRU" : "";
        POSTFIX_OOM_ADJ = APPEND_CATEGORY_NAME ? "_OomAdj" : "";
        POSTFIX_POWER = APPEND_CATEGORY_NAME ? "_Power" : "";
        POSTFIX_PROCESS_OBSERVERS = APPEND_CATEGORY_NAME ? "_ProcessObservers" : "";
        POSTFIX_PROCESSES = APPEND_CATEGORY_NAME ? "_Processes" : "";
        POSTFIX_PSS = APPEND_CATEGORY_NAME ? "_Pss" : "";
        POSTFIX_RSS = APPEND_CATEGORY_NAME ? "_Rss" : "";
        POSTFIX_SERVICE = APPEND_CATEGORY_NAME ? "_Service" : "";
        POSTFIX_SERVICE_EXECUTING = APPEND_CATEGORY_NAME ? "_ServiceExecuting" : "";
        POSTFIX_UID_OBSERVERS = APPEND_CATEGORY_NAME ? "_UidObservers" : "";
    }
}
