package com.android.server.wm;

/* JADX INFO: loaded from: classes3.dex */
public class ActivityTaskManagerDebugConfig {
    public static boolean DEBUG_ACTIVITY_STARTS = false;
    public static boolean DEBUG_ALL_ACTIVITIES = false;
    public static boolean DEBUG_AMS = false;
    public static boolean DEBUG_APP = false;
    public static boolean DEBUG_CLEANUP = false;
    public static boolean DEBUG_IDLE = false;
    public static boolean DEBUG_METRICS = false;
    public static boolean DEBUG_PERMISSIONS_REVIEW = false;
    public static boolean DEBUG_RECENTS = false;
    public static boolean DEBUG_RECENTS_TRIM_TASKS = false;
    public static boolean DEBUG_RELEASE = false;
    public static boolean DEBUG_RESULTS = false;
    public static boolean DEBUG_ROOT_TASK = false;
    static boolean DEBUG_STACK = false;
    public static boolean DEBUG_SWITCH = false;
    static boolean DEBUG_TASKS = false;
    public static boolean DEBUG_TRANSITION = false;
    public static boolean DEBUG_USER_LEAVING = false;
    private static final boolean DEBUG_VERSION;
    public static boolean DEBUG_VISIBILITY = false;
    static final java.lang.String POSTFIX_ADD_REMOVE;
    static final java.lang.String POSTFIX_APP;
    static final java.lang.String POSTFIX_CLEANUP;
    public static final java.lang.String POSTFIX_CONFIGURATION;
    static final java.lang.String POSTFIX_CONTAINERS;
    static final java.lang.String POSTFIX_FOCUS;
    static final java.lang.String POSTFIX_IDLE;
    static final java.lang.String POSTFIX_IMMERSIVE;
    public static final java.lang.String POSTFIX_LOCKTASK;
    static final java.lang.String POSTFIX_PAUSE;
    static final java.lang.String POSTFIX_RECENTS;
    static final java.lang.String POSTFIX_RELEASE;
    static final java.lang.String POSTFIX_RESULTS;
    static final java.lang.String POSTFIX_ROOT_TASK;
    static final java.lang.String POSTFIX_SAVED_STATE;
    static final java.lang.String POSTFIX_STATES;
    public static final java.lang.String POSTFIX_SWITCH;
    static final java.lang.String POSTFIX_TASKS;
    static final java.lang.String POSTFIX_TRANSITION;
    static final java.lang.String POSTFIX_USER_LEAVING;
    static final java.lang.String POSTFIX_VISIBILITY;
    static final java.lang.String TAG_ATM = "ActivityTaskManager";
    static final boolean TAG_WITH_CLASS_NAME = false;
    public static boolean APPEND_CATEGORY_NAME = false;
    public static boolean DEBUG_ALL = false;

    static {
        DEBUG_ALL_ACTIVITIES = DEBUG_ALL;
        DEBUG_TASKS = DEBUG_ALL;
        DEBUG_STACK = DEBUG_ALL;
        DEBUG_RECENTS = DEBUG_ALL;
        DEBUG_RECENTS_TRIM_TASKS = DEBUG_RECENTS;
        DEBUG_ROOT_TASK = DEBUG_ALL;
        DEBUG_SWITCH = DEBUG_ALL;
        DEBUG_TRANSITION = DEBUG_ALL;
        DEBUG_VISIBILITY = DEBUG_ALL;
        DEBUG_APP = DEBUG_ALL_ACTIVITIES;
        DEBUG_IDLE = DEBUG_ALL_ACTIVITIES;
        DEBUG_RELEASE = DEBUG_ALL_ACTIVITIES;
        DEBUG_USER_LEAVING = DEBUG_ALL;
        DEBUG_PERMISSIONS_REVIEW = DEBUG_ALL;
        DEBUG_RESULTS = DEBUG_ALL;
        DEBUG_ACTIVITY_STARTS = DEBUG_ALL;
        DEBUG_CLEANUP = DEBUG_ALL;
        DEBUG_METRICS = DEBUG_ALL;
        DEBUG_VERSION = "userdebug".equals(android.os.SystemProperties.get("ro.build.type"));
        DEBUG_AMS = android.os.SystemProperties.getBoolean("persist.sys.assert.panic", false);
        POSTFIX_APP = APPEND_CATEGORY_NAME ? "_App" : "";
        POSTFIX_CLEANUP = APPEND_CATEGORY_NAME ? "_Cleanup" : "";
        POSTFIX_IDLE = APPEND_CATEGORY_NAME ? "_Idle" : "";
        POSTFIX_RELEASE = APPEND_CATEGORY_NAME ? "_Release" : "";
        POSTFIX_USER_LEAVING = APPEND_CATEGORY_NAME ? "_UserLeaving" : "";
        POSTFIX_ADD_REMOVE = APPEND_CATEGORY_NAME ? "_AddRemove" : "";
        POSTFIX_CONFIGURATION = APPEND_CATEGORY_NAME ? "_Configuration" : "";
        POSTFIX_CONTAINERS = APPEND_CATEGORY_NAME ? "_Containers" : "";
        POSTFIX_FOCUS = APPEND_CATEGORY_NAME ? "_Focus" : "";
        POSTFIX_IMMERSIVE = APPEND_CATEGORY_NAME ? "_Immersive" : "";
        POSTFIX_LOCKTASK = APPEND_CATEGORY_NAME ? "_LockTask" : "";
        POSTFIX_PAUSE = APPEND_CATEGORY_NAME ? "_Pause" : "";
        POSTFIX_RECENTS = APPEND_CATEGORY_NAME ? "_Recents" : "";
        POSTFIX_SAVED_STATE = APPEND_CATEGORY_NAME ? "_SavedState" : "";
        POSTFIX_ROOT_TASK = APPEND_CATEGORY_NAME ? "_RootTask" : "";
        POSTFIX_STATES = APPEND_CATEGORY_NAME ? "_States" : "";
        POSTFIX_SWITCH = APPEND_CATEGORY_NAME ? "_Switch" : "";
        POSTFIX_TASKS = APPEND_CATEGORY_NAME ? "_Tasks" : "";
        POSTFIX_TRANSITION = APPEND_CATEGORY_NAME ? "_Transition" : "";
        POSTFIX_VISIBILITY = APPEND_CATEGORY_NAME ? "_Visibility" : "";
        POSTFIX_RESULTS = APPEND_CATEGORY_NAME ? "_Results" : "";
    }
}
